### ISSUE TITLE
an error when running pip install -e ".[train]"

### ISSUE THREAD

**Issue by LuyaoZhuang** [WeiminXiong/IPR#4]
I encountered an error when running pip install -e ".[train]" while trying to install my project using the setup.py file. The error seems related to the package installation in editable mode. Has anyone else faced a similar issue, and how can I resolve it?"

**Comment by zouyingcao** [comment]
same question here～ did you solve it？

**Comment by WeiminXiong** [comment]
Thank you for your feedback. In the previous version, I neglected to upload the `pyproject.toml` file, which caused issues with the installation using `pip install -e ".[train]"`. Please refer to the updated `README` guide to set up your environment. I sincerely apologize for any inconvenience caused previously.
