### ISSUE TITLE
error in the running environment

### ISSUE THREAD

**Issue by zouyingcao** [WeiminXiong/IPR#5]
When installing the environment via setup.sh, there are many package conflicts. Although I handle package conflicts manually, I still meet the error as followed. Can authors give a more detailed installation instruction, such as python, fastchat version and so on. Thanks~
```
...fastchat/train/train.py", line 134, in preprocess
[rank3]:     if conv.sep_style == SeparatorStyle.LLAMA3:
[rank3]:   File ".../lib/python3.9/enum.py", line 429, in __getattr__
[rank3]:     raise AttributeError(name) from None
[rank3]: AttributeError: LLAMA3
```

**Comment by WeiminXiong** [comment]
Thank you for your feedback. The error occurred due to an issue with the previous `setup.sh` script, which did not successfully install FastChat library. I have updated the `setup.sh` script and the `requirements.txt` accordingly. Please refer to the latest version of the `README` for details. I apologize for any inconvenience caused by the previous errors.

**Comment by zouyingcao** [comment]
> Thank you for your feedback. The error occurred due to an issue with the previous `setup.sh` script, which did not successfully install FastChat library. I have updated the `setup.sh` script and the `requirements.txt` accordingly. Please refer to the latest version of the `README` for details. I apologize for any inconvenience caused by the previous errors.

Thanks very much for updating. I tried again in the CUDA 11.8 environment and found success in setup without conflicts except the docker image pull. By the way, I want to know whether this work in the CUDA 12.4 (we all know CUDA environment keeps updating). It seems the pytorch version need change accordingly but I do not know if any other packages support. Thanks again~

**Comment by zouyingcao** [comment]
I further meet another issue.

```
=> ERROR [internal] load metadata for docker.io/library/mysql:latest                                                                                                           30.0s
------
 > [internal] load metadata for docker.io/library/mysql:latest:
------
sql.Dockerfile:1
--------------------
   1 | >>> FROM mysql
   2 |     
   3 |     ENV MYSQL_ROOT_PASSWORD="password"
--------------------
ERROR: failed to solve: mysql: failed to do request: Head "https://registry-1.docker.io/v2/library/mysql/manifests/latest": dial tcp 128.121.146.109:443: i/o timeout
ERROR: Service 'env-sql' failed to build : Build failed
```
Did you meet the same question when using docker-compose to pull the image?

**Comment by WeiminXiong** [comment]
> > Thank you for your feedback. The error occurred due to an issue with the previous `setup.sh` script, which did not successfully install FastChat library. I have updated the `setup.sh` script and the `requirements.txt` accordingly. Please refer to the latest version of the `README` for details. I apologize for any inconvenience caused by the previous errors.
> 
> Thanks very much for updating. I tried again in the CUDA 11.8 environment and found success in setup without conflicts except the docker image pull. By the way, I want to know whether this work in the CUDA 12.4 (we all know CUDA environment keeps updating). It seems the pytorch version need change accordingly but I do not know if any other packages support. Thanks again~

The environment on my machine is CUDA 12.2. I believe the code should run on CUDA 12.4, as GPU drivers typically support backward compatibility during updates.

**Comment by WeiminXiong** [comment]
> I further meet another issue.
> 
> ```
> => ERROR [internal] load metadata for docker.io/library/mysql:latest                                                                                                           30.0s
> ------
>  > [internal] load metadata for docker.io/library/mysql:latest:
> ------
> sql.Dockerfile:1
> --------------------
>    1 | >>> FROM mysql
>    2 |     
>    3 |     ENV MYSQL_ROOT_PASSWORD="password"
> --------------------
> ERROR: failed to solve: mysql: failed to do request: Head "https://registry-1.docker.io/v2/library/mysql/manifests/latest": dial tcp 128.121.146.109:443: i/o timeout
> ERROR: Service 'env-sql' failed to build : Build failed
> ```
> 
> Did you meet the same question when using docker-compose to pull the image?

I am sorry that I haven't encountered this issue. I've deployed the same environment on another machine, and `docker-compose` has successfully built the environment. Perhaps you could try the WebShop and ALFWorld tasks; they do not require a Docker environment to be deployed.
![image](https://github.com/user-attachments/assets/147f5f1c-a373-4c37-82f7-0858a75ad6e1)

**Comment by zouyingcao** [comment]
Thanks for rely. yeah, I am just first trying in ALFWorld environment.
